Ejercicio para calcular el coeficiente de Correlacion Person

1. Importamos las librerias

In [17]:
import pandas as pd
import numpy as np

2. Carga del df

In [18]:
ruta = ("../data/raw/dataset_7variables_2000_2022.csv")

df = pd.read_csv(ruta)

3. Explorar datos y valores falttantes

In [19]:
df.describe().round(1)

,year,population,births,deaths,child_deaths_under_5,health_percentage,gdp,life_expectancy
count,4244.0,4.244000e+03,4244.0,4244.0,4244.0,4244.0,4244.0,4244.0
mean,2011.1,7.617906e+07,1495146.1,599805.0,77675.4,6.2,21716.5,70.0
std,6.6,5.396940e+08,10502980.1,4226299.9,564574.1,2.8,23529.0,8.7
min,2000.0,9.566000e+03,197.0,66.0,0.0,1.2,712.0,14.7
25%,2005.0,1.921558e+06,31771.8,14227.8,323.0,4.1,4826.0,64.5
50%,2011.0,7.382110e+06,138645.0,57920.0,2857.5,5.7,13202.0,71.4
75%,2017.0,2.609631e+07,615917.0,201302.0,23048.0,7.9,30472.1,76.5
max,2022.0,8.021407e+09,146054880.0,69728100.0,10180099.0,24.5,149025.1,85.7

In [20]:
#Columnas tengo
df.columns.to_list()

['entity',
 'year',
 'population',
 'births',
 'deaths',
 'child_deaths_under_5',
 'health_percentage',
 'gdp',
 'life_expectancy']

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4244 entries, 0 to 4243
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   entity                4244 non-null   str
 1   year                  4244 non-null   int64
 2   population            4244 non-null   float64
 3   births                4244 non-null   float64
 4   deaths                4244 non-null   float64
 5   child_deaths_under_5  4244 non-null   int64
 6   health_percentage     4244 non-null   float64
 7   gdp                   4244 non-null   float64
 8   life_expectancy       4244 non-null   float64
dtypes: float64(6), int64(2), str(1)
memory usage: 298.5 KB

In [24]:
#Cantidad de nulos por cada columna
df.isnull().sum()

entity                  0
year                    0
population              0
births                  0
deaths                  0
child_deaths_under_5    0
health_percentage       0
gdp                     0
life_expectancy         0
dtype: int64

4. Seleccionar variables

In [26]:
variables_numericas = [
    "population",
    "births",
    "deaths",
    "child_deaths_under_5",
    "health_percentage",
    "gdp",
    "life_expectancy"
]
df_vn = df[variables_numericas].copy()
df_vn.head(3)

,population,births,deaths,child_deaths_under_5,health_percentage,gdp,life_expectancy
0,21378123.0,1015202.0,239161.0,123215,9.443391,1774.3087,56.2251
1,22733053.0,1069727.0,243573.0,123894,8.941258,1815.9282,57.1713
2,23560656.0,1095372.0,244435.0,122315,9.808474,1776.9182,57.8098

5. Exploramos las combinaciones

In [30]:
from itertools import combinations
from math import comb

#Calcular el número de combinaciones
n = len(variables_numericas)
total_combinaciones = comb(n,2)

print(f"Números de combinaciones: {total_combinaciones}")

Números de combinaciones: 21

In [ ]:
#inicializamos el arreglo para guardar los resultados
resultados = []

for variables_x, variables_y in combinations(variables_numericas, 2):
    # se calcula r mediante la funcion corr de pandas
    r = df_vn[variables_x].corr(df_vn[variables_y], method="pearson")

    # se guarda en un arreglo todos los valores obtenidos
    resultados.append([variables_x, variables_y, r, abs(r)])

# el arreglo de resultads se tranforma en df pandas para manipularlo
#Convertir los resultados en un DataFrame
df_resultados = pd.DataFrame(
    resultados,
    columns=["Variable X",
             "Variable Y",
             "Pearson",
             "Intensidad"] #es el valor absoluto de r
)

#Ordenar por intensidad de mayor a menor
df_resultados = df_resultados.sort_values(
    by="Intensidad", #esta es la variable por la cual se ordena
    ascending=False #aplicamos un ordenamiento ascendente
).reset_index(drop=True) # drop=True evita que el indice original se agregue como

display(df_resultados)

              Variable X            Variable Y   Pearson  Intensidad
0             population                deaths  0.997836    0.997836
1                 births                deaths  0.993034    0.993034
2             population                births  0.992562    0.992562
3                 births  child_deaths_under_5  0.967222    0.967222
4                 deaths  child_deaths_under_5  0.944894    0.944894
5             population  child_deaths_under_5  0.935124    0.935124
6                    gdp       life_expectancy  0.675566    0.675566
7      health_percentage       life_expectancy  0.286925    0.286925
8      health_percentage                   gdp  0.193442    0.193442
9   child_deaths_under_5       life_expectancy -0.067931    0.067931
10  child_deaths_under_5                   gdp -0.062524    0.062524
11  child_deaths_under_5     health_percentage -0.049833    0.049833
12                births                   gdp -0.044742    0.044742
13                births     health_percentage -0.030696    0.030696
14            population                   gdp -0.030289    0.030289
15                deaths                   gdp -0.028315    0.028315
16                births       life_expectancy -0.019662    0.019662
17            population     health_percentage -0.016296    0.016296
18                deaths     health_percentage -0.012450    0.012450
19            population       life_expectancy  0.006890    0.006890
20                deaths       life_expectancy -0.001312    0.001312